# Change these first
owner: big-digital # Your GitHub organization or username, where this repository lives
repo: BIG_Upptime # The name of this repository

sites:
  - name: Big Digital Website
    url: https://bigdigital.ca
  - name: Home Hardware API
    url: https://homehardware.bigdigital.ca/collections
  - name: Home Hardware App
    url: https://app.homehardware.bigdigital.ca/content
  - name: Kia Bessada APp
    url: https://app.kia-bessada.bigdigital.ca

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /BIG_Upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
